package com.scientianovateam.versatile.materialsystem.addition

object MaterialProperties {
    const val ASSOCIATED_NAMES = "associated_names"
    const val FORM_BLACKLIST = "form_blacklist"
    const val INVERTED_BLACKLIST = "inverted_blacklist"
    const val COMPOSITION = "composition"
    const val TEXTURE_SET = "texture_set"
    const val COLOR = "color"
    const val TIER = "tier"
    const val HARDNESS = "hardness"
    const val RESISTANCE = "resistance"
    const val HARVEST_TIER = "harvest_tier"
    const val TOOL_TIER = "tool_tier"
    const val ARMOR_TIER = "armor_tier"
    const val ELEMENT = "element"
    const val BURN_TIME = "burn_time"
    const val COMPOUND_TYPE = "compound_type"
    const val DENSITY_MULTIPLIER = "density_multiplier"
    const val PROCESSING_MULTIPLIER = "processing_multiplier"
    const val REFINED_MATERIAL = "refined_material"
    const val UNREFINED_COLOR = "unrefined_color"
    const val LIQUID_TEMPERATURE = "liquid_temperature"
    const val GAS_TEMPERATURE = "gas_temperature"
    const val LIQUID_NAME = "liquid_name"
    const val GAS_NAME = "gas_name"
    const val GAS_COLOR = "gas_color"
    const val PH = "ph"
    const val BLOCK_COMPACTION = "block_compaction"
    const val TRANSITION_MATERIAL = "transition_material"
    const val TRANSITION_AMOUNT = "transition_amount"
    const val HAS_ORE = "has_ore"
    const val SIMPLE_PROCESSING = "simple_processing"
    const val ROD_OUTPUT_COUNT = "rod_output_count"
    const val HAS_DUST = "has_dust"
    const val HAS_INGOT = "has_ingot"
    const val HAS_GEM = "has_gem"
    const val GROUP = "group"
    const val MALLEABLE = "malleable"
}