package com.scientianovateam.versatile.materialsystem.addition

object FormProperties {
    const val NAME = "name"
    const val GENERATE = "generate"
    const val INDEX_BLACKLIST = "index_blacklist"
    const val BUCKET_VOLUME = "bucket_volume"
    const val REGISTRY_NAME = "registry_name"
    const val COLOR = "color"
    const val DENSITY_MULTIPLIER = "density_multiplier"
    const val TEMPERATURE = "temperature"
    const val SINGLE_TEXTURE_SET = "single_texture_set"
    const val BURN_TIME = "burn_time"
    const val ITEM = "item"
    const val BLOCK = "block"
    const val FLUID = "fluid"
    const val ITEM_TAG = "item_tag"
    const val BLOCK_TAG = "block_tag"
    const val COMBINED_ITEM_TAGS = "combined_item_tags"
    const val COMBINED_BLOCK_TAGS = "combined_block_tags"
    const val COMBINED_FLUID_TAGS = "combined_fluid_tags"
    const val ITEM_MODEL = "item_model"
    const val BLOCKSTATE = "blockstate"
    const val BLOCK_MODELS = "block_models"
}